# Generated by Django 4.2.7 on 2025-03-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent',
            new_name='paypal_payment_id',
        ),
    ]
